---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: heimdall
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      hosts:
        - host: heimdall.kube.com
          paths:
              - path: /
                pathType: Prefix