---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: "6.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    sonarr:
      env:
        timezone: "America/New_York"
        puid: 1000
        pgid: 1000        
      ingress:
        enabled: true
        hosts:
          - host: sonarr.kube.com
            paths:
              - path: /
                pathType: Prefix
      persistence:
        config:
          enabled: true
          storageClass: "local-path"
          accessMode: ReadWriteOnce
          path: /mnt
          size: 1Gi
        media:
          enabled: false