---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tautulli
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    tautulli:
      env:
        timezone: "America/New_York"
        puid: 1000
        pgid: 1000
      ingress:
        enabled: true
        hosts:
          - host: tautulli.kube.com
            paths:
              - path: /
                pathType: Prefix
      persistence:
        config:
          enabled: true
          storageClass: " local-path"
          accessMode: ReadWriteOnce
          path: "/mnt"
          size: 1Gi