---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-v0\.16\.[0-9]+)$'
spec:
  releaseName: jackett
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jackett
    version: 3.0.1
  values:
    image:
      repository: linuxserver/jackett
      tag: version-v0.16.1933
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    service:
      type: LoadBalancer
      port: 9117
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi
