---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 5.0.1
  values:
    image:
      repository: linuxserver/radarr
      tag: version-3.0.0.3974
    ingress:
      enabled: true
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    service:
      type: LoadBalancer
      port: 7878  
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi