---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v2\.[0-9]+\.[0-9]+-ls[0-9]+)$'
spec:
  releaseName: tautulli
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: tautulli
    version: 3.0.1
  values:
    image:
      repository: linuxserver/tautulli
      tag: v2.5.6-ls14
timezone: "America/New_York"
puid: 1000
pgid: 1000
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "traefik-external"
    #traefik.ingress.kubernetes.io/router.tls: "true"
    #cert-manager.io/cluster-issuer: "letsencrypt-issuer"
  hosts:
    - host: t.kube.com
      paths:
        - /