---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "1.0.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
      storageMinimalAvailablePercentage: 5
      createDefaultDiskLabeledNodes: true
      replicaSoftAntiAffinity: true
      #backupTarget: s3://longhorn@192.168.1.39/backups
      #backupTargetCredentialSecret: longhorn-backup-secret
    ingress:
      enabled: true
      host: longhorn.kube.com 
