apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: media
  name: mnt-nfs-media-nas
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=3
  claimRef:
    namespace: media
    name: nfs-media-nas
  nfs:
    path: /mnt/myVol/kubeNFS
    server: 10.68.69.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nfs-media-nas
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-media-nas
  volumeName: mnt-nfs-media-nas