apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-nas
  namespace: system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nfs-client-provisioner-nas
  interval: 5m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: "1.2.8"
      sourceRef:
        kind: HelmRepository
        name: stable-deprecated
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner
      tag: v3.1.0-k8s1.11
    nfs:
      path: /mnt/myVol/kubeNFS
      server: 10.68.69.2     
    storageClass:
      # defaultClass: true
      name: "nfs-client-nas"