# needed to run for NFS
# sudo apt update && sudo apt install -y nfs-common
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: rimusz
        namespace: flux-system
      interval: 1m
  values:
    nfs:
      path: /mnt/myVol/kubeNFS/data
      server: 10.68.69.2
    storageClass:
      defaultClass: false
      name: "nfs-client-nas"