---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-pvc
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.68.69.2
    path: /mnt/myVol/kubeNFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-pvc
  resources:
    requests:
      storage: 1Mi