apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-system
  name: nfs-data-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  claimRef:
    namespace: kube-system
    name: nfs-data-pv  
  nfs:
    server: 10.68.69.2
    path: "/mnt/myVol/kubeNFS"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: nfs-client
provisioner: nfs-client-provisioner
parameters:
archiveOnDelete: “false”
