---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: default
spec:  
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "9.4.x"
      sourceRef:
        kind: HelmRepository
        name: traefik-external
        namespace: default
      interval: 1m   
  values:    
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik-external"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      #     - "--log.level=DEBUG"
      # - "--tracing.jaeger.samplingServerURL=http://monitoring-jaeger-agent.monitoring.svc.cluster.local:5778/sampling"
      # - "--tracing.jaeger.localAgentHostPort=monitoring-jaeger-agent.monitoring.svc.cluster.local:6831"
      # - "--tracing.jaeger.collector.endpoint=http://monitoring-jaeger-collector.monitoring.svc.cluster.local:14268/api/traces?format=jaeger.thrift"
      #- "--accesslog=true"
      # - "--metrics.prometheus=true"
      - "--serversTransport.insecureSkipVerify=true" # for k8s dash
      - "--entryPoints.web.forwardedHeaders.insecure"
      # - "--entrypoints.fooudp.address=:8191/udp"
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.68.69.3
    ports:
      traefik:
        expose: true
---
# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.kube.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: default
spec:
  interval: 1m
  url: https://helm.traefik.io/traefik