apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.helm.sh/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.traefik.io/traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/dashboard/ 
---
apiVersion: source.helm.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-client-provisioner
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-charts.storage.googleapis.com/

