---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 7.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    controllerType: deployment
    env:
      TZ: "America/New_York"
      PUID: "8675309"
      PGID: "8675309"
    ingress:
      enabled: true
      hosts:
      - host: sonarr.kube.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "sonarr.kube.com"
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce        
        size: "1Gi"
      additionalVolumeMounts:
      - name: nfs-media-pv
        mountPath: "/mnt/media"      
      additionalVolumes:
      - name: nfs-media-pv     
      persistentVolumeClaim:
        claimName: nfs-media-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi    