---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission-openvpn
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: transmission-openvpn
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: transmission-openvpn
        namespace: flux-system
      interval: 5m
