---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations: 
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.20.0
spec:
  releaseName: flux
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.5.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/zenxedo/k3s-gitops/master/flux/flux/flux-values.yml