
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:~1.14
spec:
  releaseName: flux
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.5.0
  valuesFrom:
  - externalSourceRef:
      url: https://github.com/zenxedo/k3s-gitops/blob/master/flux/flux-values.yaml