apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: halkeye
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true     
      hosts:
        - jack.kube.com
      persistence:
        enabled: true




      
   
