apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: halkeye
        namespace: flux-system
      interval: 1m
  values:
    jackett:
      env:
        TZ: "America/New_York"
      ingress:
        enabled: true
        annotations:
         # traefik.ingress.kubernetes.io/router.middlewares: system-cf-access-auth@kubernetescrd
        hosts:
        - jack.kube.com
      persistence:
        type: deployment
        config:
          enabled: true
          storageClass: mnt-nfs-media-nas
          accessMode: ReadWriteOnce
          size: 1Gi
      resources:
        requests:
          memory: "256M"
        limits:
          memory: "512M"    





      
   
