---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(version-v0\.16\.[0-9]+)$'
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    jackett:
      env:
        timezone: "America/New_York"
      puid: 1000
      pgid: 1000
      service:
        type: LoadBalancer
        port: 9117
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1500Mi
