---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: qbittorrent
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: qbittorrent
    version: 4.0.1
  values:
    image:
      repository: linuxserver/qbittorrent
      tag: version-14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1
      pullPolicy: Always
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    umask: "022"
    guiService:
      type: ClusterIP
    btService:
      type: LoadBalancer
      port: 50413
      externalIPs:
      - 192.168.69.130
      externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "trafiek-external"
      hosts:
      - "qb.kube.com"
      