apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: "6.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux
      interval: 1m
  values:
    image:
      repository: linuxserver/radarr
      tag: version-3.0.0.3974
    timezone: "America/New_York"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        existingClaim: nfs-data-pvc
      media:
        enabled: true
        existingClaim: nfs-data-pvc
    service:  
      type: LoadBalancer
      port: 7878  
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi