apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: medaia
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: "6.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    radarr:
      env:
        TZ: America/Los_Angeles