apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tautulli
      version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: false
      annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      labels:
      hosts:
        - host: tautulli.kube.com
          paths:
            - path: /
             # Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix
      tls: 
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local
    tautulli:
      env:
    #    TZ: "America/New_York"
  #      timezone: "America/New_York"
    #    puid: 1000
    #    pgid: 1000
      persistence:
        type: deployment
        config:
          enabled: true
          storageClass: "local-path"
          accessMode: ReadWriteOnce
         # path: /mnt
          size: 1Gi
     