---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-stable-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-charts.storage.googleapis.com/
  timeout: 3m